#include "Particle.h"

using namespace raven;

Particle::Particle()
	: state(ACTIVE)
	, type(PARTICLE)
	, position({0, 0})
	, prevPosition(position)
	, acceleration({ 0, 0 })
	, forceAccumulator({ 0, 0 })
	, inverseMass(1.0f)
	, damping(0.4f)
	, lifeTime(10.0f)
	, restitution(2.0f)
	, radius(10.0f)
	, material(STEEL)
{}

Particle::Particle(glm::vec2 position)
	: state(ACTIVE)
	, type(PARTICLE)
	, position(position)
	, prevPosition(position)
	, acceleration({ 0, 0 })
	, forceAccumulator({ 0, 0 })
	, inverseMass(1.0f)
	, damping(0.4f)
	, lifeTime(10.0f)
	, restitution(2.0f)
	, radius(10.0f)
	, material(STEEL)
{}

Particle::Particle(glm::vec2 position, TYPE type) 
	: state(ACTIVE)
	, type(PARTICLE)
	, position(position)
	, prevPosition(position)
	, acceleration({ 0, 0 })
	, forceAccumulator({ 0, 0 })
	, inverseMass(1.0f)
	, damping(0.4f)
	, lifeTime(10.0f)
	, restitution(2.0f)
	, radius(10.0f)
	, material(STEEL)
{}

Particle::Particle(glm::vec2 position, glm::vec2 velocity, TYPE type)
	: state(ACTIVE)
	, type(PARTICLE)
	, position(position)
	, prevPosition(position)
	, velocity(velocity)
	, acceleration({ 0, 0 })
	, forceAccumulator({ 0, 0 })
	, inverseMass(1.0f)
	, damping(0.4)
	, lifeTime(10.0f)
	, restitution(2.0f)
	, radius(10.0f)
	, material(STEEL)
{}
